#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

//---------------------------------------------------------------------------------------------------//
//                                           PL-0                                                    //
//---------------------------------------------------------------------------------------------------//
//                                                                                                   //
//      1 (∗ Berechnet GGT von zwei Zahlen ∗)                                                        //
//      2 VAR a, b, g;                                                                               //
//      3 PROCEDURE ggt;                            Funktionsbeginn ggt                              //
//      4 BEGIN                                                                                      //
//      5    WHILE a # b DO                         "#"  == Ungleich                                 //
//      6    BEGIN                                                                                   //
//      7       IF a > b THEN a := a − b;           ":=" == Zuweisung                                //
//      8       IF b > a THEN b := b − a;                                                            //
//      9    END;                                                                                    //
//      10   g := a;                                                                                 //
//      11 END;                                                                                      //
//      12 BEGIN (∗ Hauptprogramm ∗)                                                                 //
//      13 ? a;                                     // Lese a                                        //
//      14 ? b;                                     // Lese b                                        //
//      15 CALL ggt;                                // Aufruf ggt                                    //
//      16 ! g ;                                    // Ausgabe g                                     //
//      17 END.                                                                                      //
//                                                                                                   //
//---------------------------------------------------------------------------------------------------//

//Include C++ standard libraries
#include <string>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>
//Include Lex-Scanner
#include "lex.yy.h"  
#include "y.tab.h"

//Include intermediate code classes
#include "IntermediateCode.h"

//Include Symboltable (Variables and prodecures)
#include "pl0-symtab.hpp"

//Include assembler generation
#include "AssemblerCodegenerator.h"

//Include Debugger Class
#include "DebugConsole.h"
    
using namespace std;

//Prototypes required by Lex/Yacc
int yyparse();
int yylex();
int yyerror(char const* s);

//Prototypes implemented at the end of the file
IdentifierNode* insertVariable(int & result, char variableIdentifier[], IdentifierNode* nextIdentifier);
IdentifierNode* insertConstant(int & result, char constantIdentifier[], int value, IdentifierNode* nextIdentifier);
void prepareInsertProcedure(int & result, char procedureIdentifier[]);
BlockNode* insertProcedure(int & result, char procedureIdentifier[], BlockNode* blockOfProcedure);

ExpressionNode* resolveIdentifier(int & result, char identifier[]);
ExpressionNode * resolveVariable(char identifier[], int level, int offset, int & result);
ExpressionNode* resolveConstant(char identifier[], int level, int offset);

//Symbol table to manage variables, constants and procedures
symtab* symbolTable = new symtab();

//Global counters required by the parser
int global_ProcedureCounter = 0;
int global_VariableCounter = -1;
int global_JumpCounter = 1;

//Console used to debug
DebugConsole* debugConsole = new DebugConsole();


//---------------------------------------------------------------------------------------------------//
//                                  Schnittstelle LEX-Scanner                                        //
//---------------------------------------------------------------------------------------------------//


//---------------------------------------------------------------------------------------------------//
//                                           UNION                                                   //
//---------------------------------------------------------------------------------------------------//
//  Für ein Token kann es ein Ergebnis geben, welches im Parser verarbeitet werden muss.             //
//  Die Ergebnisse für verschiedene Token haben dabei verschiedene Datentypen,                       //
//  welche übergeben werden müssen.                                                                  //
//                                                                                                   //
//  Daher muss im folgenden der "union" Datentyp definiert werden,                                   //
//  welcher es ermöglicht z.B. für das gefundene Token IDENTIFIER den Wert zu übermitteln.           //
//  Die Yacc-Directve ist dafür "%union", die in der LEX-Datei mittels der globalen Variablen        //
//  "yylval" referenziert wird.                                                                      //
//                                                                                                   //
//                                                                                                   //
//  Anmerkung zu Unions:                                                                             // 
//  Ein union ist ein Datentyp mit mehreren Namen und Datentypen für die selbe Variable.             //
//                                                                                                   //
//  union number { int numInt; float numFloat; }                                                     //
//  union number myNumber;                                                                           //
//  myNumber.numInt = 5;       >> numInt: 5,   numFloat: xxx                                         //
//  myNumber.numFloat = 1.2345 >> numInt: xxx, numFloat: 1.2345                                      //
//---------------------------------------------------------------------------------------------------//



#line 107 "parser.y"
typedef union 
{ 
	int NUMBER_VALUE;                   //Additional value for T_NUMBER Token
	char IDENTIFIER_VALUE[256];         //Additional value for T_IDENTIFIER Token


	BlockNode* BLOCK_NODE;               
	StatementNode* STATEMENT_NODE; 
	ExpressionNode* EXPRESSION_NODE;
	IdentifierNode* IDENTIFIER_NODE;
	struct { StatementNode* from; StatementNode* to; } FROM_TO_NODE;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	T_NUMBER	258
#define	T_IDENTIFIER	259
#define	T_CONST	260
#define	T_VAR	261
#define	T_COMMA	262
#define	T_SEMICOLON	263
#define	T_ASSIGN	264
#define	T_POINT	265
#define	T_PLUS	266
#define	T_MINUS	267
#define	T_MULT	268
#define	T_DIV	269
#define	T_EQUAL	270
#define	T_NOT_EQUAL	271
#define	T_LESS	272
#define	T_LESS_OR_EQUAL	273
#define	T_GREATER	274
#define	T_GREATER_OR_EQUAL	275
#define	T_ODD	276
#define	T_OPEN_BRACKET	277
#define	T_CLOSE_BRACKET	278
#define	T_READ	279
#define	T_WRITE	280
#define	T_CALL	281
#define	T_PROCEDURE	282
#define	T_IF	283
#define	T_THEN	284
#define	T_WHILE	285
#define	T_DO	286
#define	T_BEGIN	287
#define	T_END	288


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int T_NUMBER;
static const int T_IDENTIFIER;
static const int T_CONST;
static const int T_VAR;
static const int T_COMMA;
static const int T_SEMICOLON;
static const int T_ASSIGN;
static const int T_POINT;
static const int T_PLUS;
static const int T_MINUS;
static const int T_MULT;
static const int T_DIV;
static const int T_EQUAL;
static const int T_NOT_EQUAL;
static const int T_LESS;
static const int T_LESS_OR_EQUAL;
static const int T_GREATER;
static const int T_GREATER_OR_EQUAL;
static const int T_ODD;
static const int T_OPEN_BRACKET;
static const int T_CLOSE_BRACKET;
static const int T_READ;
static const int T_WRITE;
static const int T_CALL;
static const int T_PROCEDURE;
static const int T_IF;
static const int T_THEN;
static const int T_WHILE;
static const int T_DO;
static const int T_BEGIN;
static const int T_END;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,T_NUMBER=258
	,T_IDENTIFIER=259
	,T_CONST=260
	,T_VAR=261
	,T_COMMA=262
	,T_SEMICOLON=263
	,T_ASSIGN=264
	,T_POINT=265
	,T_PLUS=266
	,T_MINUS=267
	,T_MULT=268
	,T_DIV=269
	,T_EQUAL=270
	,T_NOT_EQUAL=271
	,T_LESS=272
	,T_LESS_OR_EQUAL=273
	,T_GREATER=274
	,T_GREATER_OR_EQUAL=275
	,T_ODD=276
	,T_OPEN_BRACKET=277
	,T_CLOSE_BRACKET=278
	,T_READ=279
	,T_WRITE=280
	,T_CALL=281
	,T_PROCEDURE=282
	,T_IF=283
	,T_THEN=284
	,T_WHILE=285
	,T_DO=286
	,T_BEGIN=287
	,T_END=288


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::T_NUMBER=258;
const int YY_parse_CLASS::T_IDENTIFIER=259;
const int YY_parse_CLASS::T_CONST=260;
const int YY_parse_CLASS::T_VAR=261;
const int YY_parse_CLASS::T_COMMA=262;
const int YY_parse_CLASS::T_SEMICOLON=263;
const int YY_parse_CLASS::T_ASSIGN=264;
const int YY_parse_CLASS::T_POINT=265;
const int YY_parse_CLASS::T_PLUS=266;
const int YY_parse_CLASS::T_MINUS=267;
const int YY_parse_CLASS::T_MULT=268;
const int YY_parse_CLASS::T_DIV=269;
const int YY_parse_CLASS::T_EQUAL=270;
const int YY_parse_CLASS::T_NOT_EQUAL=271;
const int YY_parse_CLASS::T_LESS=272;
const int YY_parse_CLASS::T_LESS_OR_EQUAL=273;
const int YY_parse_CLASS::T_GREATER=274;
const int YY_parse_CLASS::T_GREATER_OR_EQUAL=275;
const int YY_parse_CLASS::T_ODD=276;
const int YY_parse_CLASS::T_OPEN_BRACKET=277;
const int YY_parse_CLASS::T_CLOSE_BRACKET=278;
const int YY_parse_CLASS::T_READ=279;
const int YY_parse_CLASS::T_WRITE=280;
const int YY_parse_CLASS::T_CALL=281;
const int YY_parse_CLASS::T_PROCEDURE=282;
const int YY_parse_CLASS::T_IF=283;
const int YY_parse_CLASS::T_THEN=284;
const int YY_parse_CLASS::T_WHILE=285;
const int YY_parse_CLASS::T_DO=286;
const int YY_parse_CLASS::T_BEGIN=287;
const int YY_parse_CLASS::T_END=288;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		93
#define	YYFLAG		-32768
#define	YYNTBASE	34

#define YYTRANSLATE(x) ((unsigned)(x) <= 288 ? yytranslate[x] : 50)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,    10,    17,    18,    24,    25,    30,    31,
    35,    36,    39,    40,    41,    48,    53,    58,    62,    66,
    69,    72,    75,    76,    78,    82,    85,    89,    93,    97,
   101,   105,   109,   111,   115,   119,   121,   125,   129,   131,
   133,   137,   140
};

static const short yyrhs[] = {    35,
    10,     0,     0,    36,    37,    39,    41,    44,     0,     5,
     4,    15,     3,    38,     8,     0,     0,     7,     4,    15,
     3,    38,     0,     0,     6,     4,    40,     8,     0,     0,
     7,     4,    40,     0,     0,    42,    41,     0,     0,     0,
    27,     4,    43,     8,    35,     8,     0,    28,    46,    29,
    44,     0,    30,    46,    31,    44,     0,     4,     9,    47,
     0,    32,    45,    33,     0,    26,     4,     0,    24,     4,
     0,    25,    47,     0,     0,    44,     0,    44,     8,    45,
     0,    21,    47,     0,    47,    15,    47,     0,    47,    16,
    47,     0,    47,    17,    47,     0,    47,    18,    47,     0,
    47,    19,    47,     0,    47,    20,    47,     0,    48,     0,
    47,    11,    48,     0,    47,    12,    48,     0,    49,     0,
    48,    13,    49,     0,    48,    14,    49,     0,     4,     0,
     3,     0,    22,    47,    23,     0,    11,    49,     0,    12,
    49,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   211,   232,   235,   256,   270,   284,   297,   316,   330,   344,
   357,   380,   389,   402,   416,   443,   477,   522,   544,   553,
   575,   596,   610,   624,   632,   670,   674,   678,   682,   686,
   690,   694,   723,   732,   740,   751,   759,   767,   778,   791,
   799,   808,   817
};

static const char * const yytname[] = {   "$","error","$illegal.","T_NUMBER",
"T_IDENTIFIER","T_CONST","T_VAR","T_COMMA","T_SEMICOLON","T_ASSIGN","T_POINT",
"T_PLUS","T_MINUS","T_MULT","T_DIV","T_EQUAL","T_NOT_EQUAL","T_LESS","T_LESS_OR_EQUAL",
"T_GREATER","T_GREATER_OR_EQUAL","T_ODD","T_OPEN_BRACKET","T_CLOSE_BRACKET",
"T_READ","T_WRITE","T_CALL","T_PROCEDURE","T_IF","T_THEN","T_WHILE","T_DO","T_BEGIN",
"T_END","Program","Block","@1","Optional_Const_Definition","Repetition_Multiple_Const_Defintion",
"Optional_Var_Definition","Repetition_Multiple_Var_Defintion","Repetition_Procedure_Definition",
"Procedure_Definition","@2","Statement","Repetition_Statement","Condition","Expression",
"Term","Factor",""
};
#endif

static const short yyr1[] = {     0,
    34,    36,    35,    37,    37,    38,    38,    39,    39,    40,
    40,    41,    41,    43,    42,    44,    44,    44,    44,    44,
    44,    44,    44,    45,    45,    46,    46,    46,    46,    46,
    46,    46,    47,    47,    47,    48,    48,    48,    49,    49,
    49,    49,    49
};

static const short yyr2[] = {     0,
     2,     0,     5,     6,     0,     5,     0,     4,     0,     3,
     0,     2,     0,     0,     6,     4,     4,     3,     3,     2,
     2,     2,     0,     1,     3,     2,     3,     3,     3,     3,
     3,     3,     1,     3,     3,     1,     3,     3,     1,     1,
     3,     2,     2
};

static const short yydefact[] = {     2,
     0,     5,     1,     0,     9,     0,     0,    13,     0,    11,
     0,    23,    13,     7,     0,     0,    14,     0,     0,     0,
     0,     0,     0,    23,     3,    12,     0,     0,    11,     8,
     0,     0,    21,    40,    39,     0,     0,     0,    22,    33,
    36,    20,     0,     0,     0,     0,    24,     0,     0,     4,
    10,     2,    18,    42,    43,     0,     0,     0,     0,     0,
    26,    23,     0,     0,     0,     0,     0,     0,    23,    23,
    19,     0,     0,    41,    34,    35,    37,    38,    16,    27,
    28,    29,    30,    31,    32,    17,    25,     7,    15,     6,
     0,     0,     0
};

static const short yydefgoto[] = {    91,
     1,     2,     5,    28,     8,    16,    12,    13,    31,    47,
    48,    44,    45,    40,    41
};

static const short yypact[] = {-32768,
    -6,     3,-32768,    18,    17,    15,    28,     9,    34,    31,
    35,     1,     9,    33,    37,    45,-32768,    46,    38,     6,
    39,    48,    48,     1,-32768,-32768,    50,    53,    31,-32768,
    54,     6,-32768,-32768,-32768,     6,     6,     6,    -5,     2,
-32768,-32768,     6,    27,    56,    32,    57,    25,    49,-32768,
-32768,-32768,    -5,-32768,-32768,    -9,     6,     6,     6,     6,
    -5,     1,     6,     6,     6,     6,     6,     6,     1,     1,
-32768,    63,    69,-32768,     2,     2,-32768,-32768,-32768,    -5,
    -5,    -5,    -5,    -5,    -5,-32768,-32768,    33,-32768,-32768,
    78,    79,-32768
};

static const short yypgoto[] = {-32768,
    29,-32768,-32768,    -8,-32768,    55,    70,-32768,-32768,   -12,
    12,    62,   -19,   -37,   -25
};


#define	YYLAST		85


static const short yytable[] = {    25,
    39,    57,    58,     3,    18,    57,    58,     4,    34,    35,
    54,    55,    53,    74,    59,    60,    36,    37,    56,    75,
    76,     6,     7,    61,    19,    20,    21,    38,    22,     9,
    23,    10,    24,    77,    78,    11,    14,    15,    17,    27,
    29,    33,    42,    80,    81,    82,    83,    84,    85,    79,
    34,    35,    30,    49,    32,    62,    86,    71,    36,    37,
    50,    52,    69,    72,    70,    88,    57,    58,    43,    38,
    63,    64,    65,    66,    67,    68,    89,    92,    93,    90,
    73,    87,    26,    51,    46
};

static const short yycheck[] = {    12,
    20,    11,    12,    10,     4,    11,    12,     5,     3,     4,
    36,    37,    32,    23,    13,    14,    11,    12,    38,    57,
    58,     4,     6,    43,    24,    25,    26,    22,    28,    15,
    30,     4,    32,    59,    60,    27,     3,     7,     4,     7,
     4,     4,     4,    63,    64,    65,    66,    67,    68,    62,
     3,     4,     8,     4,     9,    29,    69,    33,    11,    12,
     8,     8,    31,    15,     8,     3,    11,    12,    21,    22,
    15,    16,    17,    18,    19,    20,     8,     0,     0,    88,
    52,    70,    13,    29,    23
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 212 "parser.y"
{ 
                            debugConsole->startGrammar("Program");

                            // Add Main-Procedure
                            DataModel::getInstance()->procedures.push_back(yyvsp[-1].BLOCK_NODE); 
                            DataModel::getInstance()->mainProcedure = yyvsp[-1].BLOCK_NODE; 
                            yyvsp[-1].BLOCK_NODE->identifier = "main"; 

                            //prepare generation of assembler code
                            DataModel::getInstance()->prepareAssemberGeneration();       

                            debugConsole->endGrammar("Program");                                                    
                        ;
    break;}
case 2:
#line 232 "parser.y"
{ 
                            symbolTable->level_up(); 
                        ;
    break;}
case 3:
#line 236 "parser.y"
{ 
                            debugConsole->startGrammar("Block");
                                            
                            yyval.BLOCK_NODE = new BlockNode("", yyvsp[0].FROM_TO_NODE.from, yyvsp[-3].IDENTIFIER_NODE, yyvsp[-2].IDENTIFIER_NODE);
                            symbolTable->level_down();
                            
                            debugConsole->startGrammar("Block");
                        ;
    break;}
case 4:
#line 257 "parser.y"
{  
                            debugConsole->startGrammar("Optional_Const_Definition");

                            int result;                                        // identifier // value // next constant
                            IdentifierNode* newConstant = insertConstant(result, yyvsp[-4].IDENTIFIER_VALUE, yyvsp[-2].NUMBER_VALUE, yyvsp[-1].IDENTIFIER_NODE);

                            if(result != 0) return result;

                            yyval.IDENTIFIER_NODE = newConstant;


                            debugConsole->endGrammar("Optional_Const_Definition");
                        ;
    break;}
case 5:
#line 271 "parser.y"
{ 
                            debugConsole->startGrammar("Optional_Const_Definition", "Epsilon");
                            
                            //Nothing to do, no constants
                            yyval.IDENTIFIER_NODE = nullptr; 

                            debugConsole->endGrammar("Optional_Const_Definition", "Epsilon");
                        ;
    break;}
case 6:
#line 285 "parser.y"
{ 
                            debugConsole->startGrammar("Repetition_Multiple_Const_Defintion", "Multiple Assignment");
 
                            int result;                                        // identifier // value // next constant
                            IdentifierNode* newConstant = insertConstant(result, yyvsp[-3].IDENTIFIER_VALUE, yyvsp[-1].NUMBER_VALUE, yyvsp[0].IDENTIFIER_NODE);

                            if(result != 0) return result;

                            yyval.IDENTIFIER_NODE = newConstant;
              
                            debugConsole->endGrammar("Repetition_Multiple_Const_Defintion", "Multiple Assignment");
                        ;
    break;}
case 7:
#line 298 "parser.y"
{ 
                            debugConsole->startGrammar("Repetition_Multiple_Const_Defintion", "Epsilon");
                            
                            //Nothing to do, Last Identifier -- next --> nullptr
                            yyval.IDENTIFIER_NODE = nullptr; 

                            debugConsole->endGrammar("Repetition_Multiple_Const_Defintion", "Epsilon");
                        ;
    break;}
case 8:
#line 317 "parser.y"
{  
                            debugConsole->startGrammar("Optional_Var_Definition");


                            int result;
                            IdentifierNode* newVariable = insertVariable(result, yyvsp[-2].IDENTIFIER_VALUE, yyvsp[-1].IDENTIFIER_NODE);

                            if(result != 0) return result;

                            yyval.IDENTIFIER_NODE = newVariable;

                            debugConsole->endGrammar("Optional_Var_Definition");
                        ;
    break;}
case 9:
#line 331 "parser.y"
{
                            debugConsole->startGrammar("Optional_Var_Definition", "Epsilon");

                            //Nothing to do, no variables
                            yyval.IDENTIFIER_NODE = nullptr;

                            debugConsole->endGrammar("Optional_Var_Definition", "Epsilon");
                        ;
    break;}
case 10:
#line 345 "parser.y"
{ 
                            debugConsole->startGrammar("Repetition_Multiple_Var_Defintion", "Multiple Assignment");
                            
                            int result;
                            IdentifierNode* newVariable = insertVariable(result, yyvsp[-1].IDENTIFIER_VALUE, yyvsp[0].IDENTIFIER_NODE);

                            if(result != 0) return result;

                            yyval.IDENTIFIER_NODE = newVariable;

                            debugConsole->endGrammar("Repetition_Multiple_Var_Defintion", "Multiple Assignment");
                        ;
    break;}
case 11:
#line 358 "parser.y"
{
                            debugConsole->startGrammar("Repetition_Multiple_Var_Defintion", "Epsilon");
                            
                            //Nothing to do, Last Identifier -- next --> nullptr
                            yyval.IDENTIFIER_NODE = nullptr;

                            debugConsole->endGrammar("Repetition_Multiple_Var_Defintion", "Epsilon");
                        ;
    break;}
case 12:
#line 381 "parser.y"
{  
                            debugConsole->startGrammar("Repetition_Procedure_Definition");

                            yyval.BLOCK_NODE = yyvsp[-1].BLOCK_NODE; 
                            DataModel::getInstance()->procedures.push_back(yyval.BLOCK_NODE); 

                            debugConsole->endGrammar("Repetition_Procedure_Definition");
                        ;
    break;}
case 13:
#line 390 "parser.y"
{  
                            debugConsole->startGrammar("Repetition_Procedure_Definition", "Epsilon");
                             
                            yyval.BLOCK_NODE = nullptr; 

                            debugConsole->endGrammar("Repetition_Procedure_Definition", "Espilon");
                        ;
    break;}
case 14:
#line 403 "parser.y"
{ 
                            debugConsole->startGrammar("Procedure_Definition", "Identifier");

                            //We insert here the correct name of the procedure, to avoid duplicate procedures on the same level

                            int result;
                            prepareInsertProcedure(result, yyvsp[0].IDENTIFIER_VALUE);

                            if(result != 0) return result;

                            debugConsole->endGrammar("Procedure_Definition", "Identifier");

                        ;
    break;}
case 15:
#line 417 "parser.y"
{
                            debugConsole->startGrammar("Procedure_Definition", "Block");

                            //We manipulate the identifier by appending a global procedure counter
                            //This is required to have multiple procedures on different levels

                            int res;
                            BlockNode* blockOfProcedure = insertProcedure(res, yyvsp[-4].IDENTIFIER_VALUE, yyvsp[-1].BLOCK_NODE);

                            yyval.BLOCK_NODE = blockOfProcedure;

                            debugConsole->endGrammar("Procedure_Definition", "Block");                            
                        ;
    break;}
case 16:
#line 444 "parser.y"
{
                            debugConsole->startGrammar("If_Then");

                            // Return
                            //  From = IF
                            //  To   = END IF

                            // |-------------------------------------------------------------------|    Jump Counter
                            // |                                                                   |    To create assembler code also Jump Reference 
                            // IF -> Some Statement -> Some Statement -> ... -> Some Statement END IF (NOP)
                            // Expression

                            StatementNode* ifStatement = new StatementNode(AssemblerCodegenerator::JUMP_FALSE, global_JumpCounter);
                            
                            ExpressionNode* condition = yyvsp[-2].EXPRESSION_NODE;
                            ifStatement->expressionNode = condition;
                            
                            // If Statement -> Some Statement -> Some Statement -> ....
                            ifStatement->next = yyvsp[0].FROM_TO_NODE.from;

                            StatementNode* endIfStatement = new StatementNode(AssemblerCodegenerator::NOP, global_JumpCounter);
                            
                            //Reference to create assembler code
                            ifStatement->nextStatementChain = endIfStatement;
                            
                            global_JumpCounter++;

                            yyval.FROM_TO_NODE.from = ifStatement;
                            yyval.FROM_TO_NODE.to = endIfStatement;
                            
                            debugConsole->endGrammar("If_Then");
                        ;
    break;}
case 17:
#line 478 "parser.y"
{
                            debugConsole->startGrammar("While_Do");

                            // Return FROM: NOP_START
                            //       TO:   NOP_END

                            //  |-------------------------Jump Back------------------------------------------------|    Jump Counter = x 
                            //  |                                                                                  |    
                            // NOP_START -> WHILE_START (JUMP_F) -> Some Statmeent -> ... -> Some Statement     WHILE_END (Jump) -> NOP_END
                            //                |                                                                                       |    To create assembler code also Jump Reference 
                            //                |-----------Jump Front------------------------------------------------------------------|    Jump Counter = x + 1
                            //              Expression


                            int currentCounter = global_JumpCounter;
                            global_JumpCounter++;
                            global_JumpCounter++;

                            StatementNode* nopStartNode = new StatementNode(AssemblerCodegenerator::NOP, currentCounter);
                            StatementNode* whileStartNode = new StatementNode(AssemblerCodegenerator::JUMP_FALSE, currentCounter + 1);

                            StatementNode* whileEndNode = new StatementNode(AssemblerCodegenerator::JUMP, currentCounter);
                            StatementNode* nopEndNode = new StatementNode(AssemblerCodegenerator::NOP, currentCounter + 1);

                            //NOP_START -> WHILE_START
                            nopStartNode->next = whileStartNode;

                            //WHILE_START -> Condition (Expression)
                            ExpressionNode * condition = yyvsp[-2].EXPRESSION_NODE;
                            whileStartNode->expressionNode = condition;

                            //WHILE_START -- jump reference to create assembler conde --> WHILE_END
                            whileStartNode->nextStatementChain = whileEndNode;
                            
                            //WHILE_START -> Next Statement
                            whileStartNode->next = yyvsp[0].FROM_TO_NODE.from;

                            whileEndNode->next = nopEndNode;

                            yyval.FROM_TO_NODE.from = nopStartNode;
                            yyval.FROM_TO_NODE.to = nopEndNode;

                            debugConsole->endGrammar("While_Do");
                        ;
    break;}
case 18:
#line 523 "parser.y"
{ 
                            debugConsole->startGrammar("Assign");

                            int level;
                            int offset;
                            int result = symbolTable->lookup(yyvsp[-2].IDENTIFIER_VALUE, st_var, level, offset);
                            if(result != 0)
						    {
								printf("Error at assignment with identifier: %s\n", yyvsp[-2].IDENTIFIER_VALUE);
								return result;
							}
                            StatementNode* assignmentNode = new StatementNode(AssemblerCodegenerator::ASSIGN, yyvsp[-2].IDENTIFIER_VALUE); 
                            assignmentNode->level = level;
                            assignmentNode->offset = offset;
                            assignmentNode->expressionNode = yyvsp[0].EXPRESSION_NODE; 

                            yyval.FROM_TO_NODE.from = assignmentNode;
                            yyval.FROM_TO_NODE.to = assignmentNode;

                            debugConsole->endGrammar("Assign");
                        ;
    break;}
case 19:
#line 545 "parser.y"
{
                            debugConsole->startGrammar("Statement", "BEGIN_END");

                            //Nothing to do, handled by Repetition_Statement
                            yyval.FROM_TO_NODE = yyvsp[-1].FROM_TO_NODE; 

                            debugConsole->endGrammar("Statement", "BEGIN_END");
                        ;
    break;}
case 20:
#line 554 "parser.y"
{ 
                            debugConsole->startGrammar("Call");

                            int level;
                            int offset;
						    int result = symbolTable->lookup(yyvsp[0].IDENTIFIER_VALUE, st_proc, level, offset);
						    if(result != 0)
							{
						        printf("Error at CALL with identifier: %s\n", yyvsp[0].IDENTIFIER_VALUE);
							    return result;
							}

                            StatementNode* callNode = new StatementNode(AssemblerCodegenerator::CALL, yyvsp[0].IDENTIFIER_VALUE+std::to_string(offset)); 
                            callNode->level = level;
                            callNode->offset = offset;

                            yyval.FROM_TO_NODE.from = callNode;
                            yyval.FROM_TO_NODE.to = callNode;

                            debugConsole->endGrammar("Call");
                        ;
    break;}
case 21:
#line 576 "parser.y"
{ 
                            debugConsole->startGrammar("Read");
                            
                            int level;
                            int offset;
							int result = symbolTable->lookup(yyvsp[0].IDENTIFIER_VALUE, st_var, level, offset);
						    if(result != 0)
						    {
								printf("Error at READ with identifier: %s\n", yyvsp[0].IDENTIFIER_VALUE);
								return result;
							}
                            StatementNode* readNode = new StatementNode(AssemblerCodegenerator::READ, yyvsp[0].IDENTIFIER_VALUE); 
                            readNode->level = level;
                            readNode->offset = offset;

                            yyval.FROM_TO_NODE.from = readNode;
                            yyval.FROM_TO_NODE.to = readNode;
            
                            debugConsole->endGrammar("Read");
                        ;
    break;}
case 22:
#line 597 "parser.y"
{ 
                            debugConsole->startGrammar("Write");
                            
                            ExpressionNode* expression = yyvsp[0].EXPRESSION_NODE;
                            
                            StatementNode* writeNode = new StatementNode(AssemblerCodegenerator::WRITE, expression->identifier);
                            writeNode->expressionNode = expression; 
                            
                            yyval.FROM_TO_NODE.from = writeNode;
                            yyval.FROM_TO_NODE.to = writeNode;

                            debugConsole->endGrammar("Write");
                        ;
    break;}
case 23:
#line 611 "parser.y"
{
                            debugConsole->startGrammar("Statement", "Epsilon");
                            
                            //Nothing to do
                            yyval.FROM_TO_NODE.from = yyval.FROM_TO_NODE.to = nullptr;

                            debugConsole->endGrammar("Statement", "Epsilon");
                        ;
    break;}
case 24:
#line 625 "parser.y"
{ 
                            debugConsole->startGrammar("Repetition_Statement", "Single Statement");

                            yyval.FROM_TO_NODE = yyvsp[0].FROM_TO_NODE;

                            debugConsole->endGrammar("Repetition_Statement", "Single Statement");
                        ;
    break;}
case 25:
#line 633 "parser.y"
{
                            debugConsole->startGrammar("Repetition_Statement");

                            //Both are empty return nullptr
                            if( yyvsp[-2].FROM_TO_NODE.from == nullptr && yyvsp[-2].FROM_TO_NODE.to == nullptr && 
                                yyvsp[0].FROM_TO_NODE.from == nullptr && yyvsp[0].FROM_TO_NODE.to == nullptr )
                            {
                                yyval.FROM_TO_NODE = yyvsp[-2].FROM_TO_NODE;
                            }
                            //statment is empty -> return statementlist
                            else if(yyvsp[-2].FROM_TO_NODE.from == nullptr && yyvsp[-2].FROM_TO_NODE.to == nullptr)
                            {
                                yyval.FROM_TO_NODE = yyvsp[0].FROM_TO_NODE;
                            }
                            //statementlist is empty -> return statement
                            else if(yyvsp[0].FROM_TO_NODE.from == nullptr && yyvsp[0].FROM_TO_NODE.to == nullptr)
                            {
                                yyval.FROM_TO_NODE = yyvsp[-2].FROM_TO_NODE;
                            }
                            //statment is not empty and statementlist is also not empty
                            //Link statment-> statementlist
                            //Statment.to == statementlist.from
                            //Return From = statmenet.from, To = Statementlist.to
                            else {
                                yyval.FROM_TO_NODE = yyvsp[-2].FROM_TO_NODE;
                                yyval.FROM_TO_NODE.to->next = yyvsp[0].FROM_TO_NODE.from;
                                yyval.FROM_TO_NODE.to = yyvsp[0].FROM_TO_NODE.to;
                            }
                            
                            debugConsole->endGrammar("Repetition_Statement");
                        ;
    break;}
case 26:
#line 671 "parser.y"
{ 
                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::ODD, yyvsp[0].EXPRESSION_NODE, nullptr); 
                        ;
    break;}
case 27:
#line 675 "parser.y"
{ 
                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::EQUAL, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE); 
                        ;
    break;}
case 28:
#line 679 "parser.y"
{ 
                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::NOT_EQUAL, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE); 
                        ;
    break;}
case 29:
#line 683 "parser.y"
{ 
                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::LESS, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE);  
                        ;
    break;}
case 30:
#line 687 "parser.y"
{ 
                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::LESS_OR_EQUAL, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE); 
                        ;
    break;}
case 31:
#line 691 "parser.y"
{ 
                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::GREATER, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE);  
                        ;
    break;}
case 32:
#line 695 "parser.y"
{ 
                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::GREATER_OR_EQUAL, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE); 
                        ;
    break;}
case 33:
#line 724 "parser.y"
{ 
                            debugConsole->startGrammar("Expression", "Term");

                            //Nothing to do
                            yyval.EXPRESSION_NODE = yyvsp[0].EXPRESSION_NODE;

                            debugConsole->endGrammar("Expression", "Term");
                        ;
    break;}
case 34:
#line 733 "parser.y"
{ 
                            debugConsole->startGrammar("Expression", "Plus");

                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::PLUS, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE); 

                            debugConsole->endGrammar("Expression", "Plus");
                        ;
    break;}
case 35:
#line 741 "parser.y"
{ 
                            debugConsole->startGrammar("Expression", "Minus");

                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::MINUS, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE); 

                            debugConsole->endGrammar("Expression", "Minus");
                        ;
    break;}
case 36:
#line 752 "parser.y"
{ 
                            debugConsole->startGrammar("Term");

                            yyval.EXPRESSION_NODE = yyvsp[0].EXPRESSION_NODE; 

                            debugConsole->endGrammar("Term");
                        ;
    break;}
case 37:
#line 760 "parser.y"
{ 
                            debugConsole->startGrammar("Term", "Mult");

                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::MULT, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE); 

                            debugConsole->endGrammar("Term", "Mult");
                        ;
    break;}
case 38:
#line 768 "parser.y"
{   
                            debugConsole->startGrammar("Term", "Div");

                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::DIV, yyvsp[-2].EXPRESSION_NODE, yyvsp[0].EXPRESSION_NODE); 

                            debugConsole->endGrammar("Term", "Div");
                        ;
    break;}
case 39:
#line 779 "parser.y"
{ 
                            debugConsole->startGrammar("Factor", "Identifier");

                            int result;
                            ExpressionNode* identifier = resolveIdentifier(result, yyvsp[0].IDENTIFIER_VALUE);
                            
                            if(result != 0) return result;

                            yyval.EXPRESSION_NODE = identifier;

                            debugConsole->endGrammar("Factor", "Identifier");
                        ;
    break;}
case 40:
#line 792 "parser.y"
{ 
                            debugConsole->startGrammar("Factor", "Number");

                            yyval.EXPRESSION_NODE = new ExpressionNode(std::to_string(yyvsp[0].NUMBER_VALUE), AssemblerCodegenerator::NUMBER, nullptr, nullptr); 

                            debugConsole->endGrammar("Factor", "Number");
                        ;
    break;}
case 41:
#line 800 "parser.y"
{ 
                            debugConsole->startGrammar("Factor", "( )");

                            //Nothing to do
                            yyval.EXPRESSION_NODE = yyvsp[-1].EXPRESSION_NODE;

                            debugConsole->endGrammar("Factor", "( )");
                        ;
    break;}
case 42:
#line 809 "parser.y"
{ 
                            debugConsole->startGrammar("Factor", "Plus");

                            //Nothing to do
                            yyval.EXPRESSION_NODE = yyvsp[0].EXPRESSION_NODE; 

                            debugConsole->endGrammar("Factor", "Plus");
                        ;
    break;}
case 43:
#line 818 "parser.y"
{ 
                            debugConsole->startGrammar("Factor", "Minus");

                            //Change sign of underlying expression
                            yyval.EXPRESSION_NODE = new ExpressionNode(AssemblerCodegenerator::CHANGESIGN, nullptr, yyvsp[0].EXPRESSION_NODE); 

                            debugConsole->endGrammar("Factor", "Minus");
                        ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 827 "parser.y"


IdentifierNode* insertVariable(int & result, char variableIdentifier[], IdentifierNode* nextIdentifier)
{
    global_VariableCounter += 1;
    result = symbolTable->insert(variableIdentifier, st_var, global_VariableCounter); 

    if(result != 0){
		printf("Error at inserting variable with identifier: %s\n", variableIdentifier);
	}

    IdentifierNode * newIdentifier = new IdentifierNode(variableIdentifier);  
    newIdentifier->next = nextIdentifier;
    
    return newIdentifier;
}

IdentifierNode* insertConstant(int & result, char constantIdentifier[], int value, IdentifierNode* nextIdentifier)
{

    result = symbolTable->insert(constantIdentifier, st_const, value); 

    if(result != 0){
		printf("Error at inserting constant with identifier: %s\n", constantIdentifier);
	}

    IdentifierNode * newIdentifier = new IdentifierNode(constantIdentifier);  
    newIdentifier->value = value;
    newIdentifier->next = nextIdentifier;
    
    return newIdentifier;
}


void prepareInsertProcedure(int & result, char procedureIdentifier[])
{

    result = symbolTable->insert(procedureIdentifier, st_proc, ++global_ProcedureCounter);
    if(result != 0)
	{
		printf("Error at inserting procedure with identifier %s\n", procedureIdentifier);
	}
    //Reset variable counter for each procedure
    global_VariableCounter = -1;
};

BlockNode* insertProcedure(int & result, char procedureIdentifier[], BlockNode* blockOfProcedure)
{

    int level;
    int offset;

    result = symbolTable->lookup(procedureIdentifier, st_proc, level, offset);

    blockOfProcedure->identifier = std::string(procedureIdentifier)+std::to_string(offset);

    return blockOfProcedure;
};

ExpressionNode* resolveIdentifier(int & result, char identifier[])
{

    int level;
    int offset;

    result = symbolTable->lookup(identifier, st_const, level, offset);
	if(result != 0)
	{
        ExpressionNode* variable = resolveVariable(identifier, level, offset, result);
        if(result != 0){
            printf("Error in factor with identifier:  %s\n", identifier);
            return nullptr;
        }
        return variable;
	}
    else 
    {
        ExpressionNode* constant = resolveConstant(identifier, level, offset);
        return constant;
    }

}

ExpressionNode* resolveVariable(char identifier[], int level, int offset, int & result){
    	result = symbolTable->lookup(identifier, st_var, level, offset);
        if(result != 0)
		{
            return nullptr;
		}
        else
        {
            ExpressionNode* variable = new ExpressionNode(identifier, AssemblerCodegenerator::VAR, nullptr, nullptr);
            variable->level = level;
            variable->offset = offset;

            return variable;
        }
}

ExpressionNode* resolveConstant(char identifier[], int level, int offset){
        ExpressionNode* constant = new ExpressionNode(identifier, AssemblerCodegenerator::CONST, nullptr, nullptr);
        constant->value = offset; //In case of a constant, the "offset" is the value
        constant->level = level;
        constant->offset = offset;

        return constant;
}

int yyerror(char const* s) 
{
	printf("%s\n", s);
	return 1;
}


int startParse(int argc, char* argv[])
{
    //extern FILE * yyin;
	if (argc < 2)
	{
		std::cout << "Not enough arguments" << std::endl;
		return 1;
	}

	FILE* file;
	std::string toOpen = std::string(argv[1]) + ".pl0";
	file = fopen(toOpen.c_str(), "r+");

	if (!file)
	{
		std::cout << toOpen << " can not be opend" << std::endl;
		return 1;
	}

	yyin = file;

	
    //debugConsole->printGrammar();
    
	if (yyparse() == 0)
	{

		std::string outputFileName = std::string(argv[1]) + ".asm";

    	FILE* outputFile = fopen((outputFileName).c_str(), "w");

		AssemblerCodegenerator::getInstance()->setFile(outputFile);

		DataModel::getInstance()->generateAssember(); 
        fclose(outputFile);
		return 0;
	}
	else
	{
		return 1;
	}
}

